baseURL: https://www.katpisiolek.com
title: 'katpisiolek.com'
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: ''

params:
  logo: /logo.jpg
  subtitle: London-based photography studio specialising in advertising and editorial.
  copyright: All rights reserved.
  author: Kat Pisiolek
  dontShowSource: true
  socials:
    - icon: far fa-envelope fa-xl
      url: mailto:kat@katpisiolek.com
      landing: true
    - icon: fab fa-instagram fa-xl
      url: https://www.instagram.com/kat_pisiolek/
      landing: true
    - icon: fab fa-linkedin-in fa-xl
      url: https://www.linkedin.com/in/kat-pisiolek-66961743
      landing: true
  homepage: "/all"
  specialPages:
    - all
  bypassWelcomePage: true
  disableWelcomePageBackground: true
  plausible: ''
  disableRadius: true
  moveIt: false
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

timeout: 120s

permalinks:
  all: ":filename/"

menu:
  main:
    - name: all
      url: /all/
      weight: 100
    - name: beauty
      url: /tags/beauty/
      weight: 200
    - name: still-life
      url: /tags/still-life/
      weight: 300
    - name: texture
      url: /tags/texture/
      weight: 400
    - name: contact
      url: /contact/
      weight: 500
